name: "Frogbot Unified Workflow"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: write
  pull-requests: write
  security-events: write
  id-token: write

jobs:
  # Job 1: Runs when a Pull Request is opened or updated
  scan-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Frogbot PR Scan
        uses: jfrog/frogbot@v3
        with:
          oidc-provider-name: vigneshs-oidc
        env:
          JFROG_CLI_LOG_LEVEL: "DEBUG"
          JF_URL: "https://hts2.jfrog.io"
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
          # JF_INCLUDE_ALL_VULNERABILITIES: "true"

  # Job 2: Runs automatically when code is pushed/merged to the main branch
  create-fix-pull-requests:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Frogbot Scan and Fix
        uses: jfrog/frogbot@v3
        with:
          oidc-provider-name: vigneshs-oidc
        env:
          JFROG_CLI_LOG_LEVEL: "DEBUG"
          JF_URL: "https://hts2.jfrog.io"
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
          # JF_INCLUDE_ALL_VULNERABILITIES: "true"
